# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JetlinkSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod ‘JetlinkSDK’ 

    # Pods for JetlinkSample
  
  target 'JetlinkSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JetlinkSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
